FROM registry.access.redhat.com/ubi8/ubi-minimal

# Labels
LABEL name="awsvmscheduler" \
    maintainer="tech@mycompany.com" \
    vendor="mycompany" \
    version="1.0.0" \
    release="1" \
    summary="This service enables AWS cloud vm start/stop." \
    description="This service enables AWS cloud vm start/stop."

RUN microdnf install golang

# copy code to the build path
COPY . .

RUN go mod download

RUN go build -o AWSVMScheduler

ENV ec2_instanceIds "dummy-ids"

ENV ec2_command "start"

# copy binary.
COPY AWSVMScheduler AWSVMScheduler

CMD ["sh", "-c", "./AWSVMScheduler -c  $ec2_command -i $ec2_instanceIds "]
