FROM registry.redhat.io/ubi9/ubi-micro:9.1.0-13

# Labels
LABEL name="awsvmscheduler" \
    maintainer="tech@mycompany.com" \
    vendor="mycompany" \
    version="1.0.0" \
    release="1" \
    summary="This service enables AWS cloud vm start/stop." \
    description="This service enables AWS cloud vm start/stop."

ENV ec2_instanceIds "dummy-ids"

ENV ec2_command "start"

# copy binary.
COPY AWSVMScheduler AWSVMScheduler

CMD ["sh", "-c", "./AWSVMScheduler -c  $ec2_command -i $ec2_instanceIds "]